### ISSUE TITLE
chore(PopConfirmButton): Table组件中【无法取消】删除操作

### ISSUE THREAD

**Issue by Idle-wang** [dotnetcore/BootstrapBlazor#4335]
### Which class is this unit test associated with?

我根据微软的模板创建的项目，然后按照【服务器端 Blazor 安装教程】进行配置。在使用Table组件时，发现点击删除按钮后，只有第一次可以进行取消，再次点击删除按钮后，提示面板会被卡住，无法取消。
![image](https://github.com/user-attachments/assets/22ca1b3b-b066-415d-b36f-a5ff00ab8841)

甚至点击其他页面时，提示面板依然存在
![image](https://github.com/user-attachments/assets/a6a055bf-e695-4363-ade1-2a524b9213be)
请问这是什么问题，谢谢
以下为我的代码
![image](https://github.com/user-attachments/assets/96ad8149-350c-4f07-80fa-b6ef341012d2)

**Comment by densen2014** [comment]
1.加群 795206915
2.用文档的官方模板建一个试一下

**Comment by Idle-wang** [comment]
好像浏览器的问题，换成谷歌浏览器就正常了，但是点取消的时候控制台还是会报错，不知道这是正常的情况吗
![image](https://github.com/user-attachments/assets/2dfdfc5b-f337-4851-93d1-843269d786f9)

**Comment by densen2014** [comment]
参考上面步骤

**Comment by ahurynovich** [comment]
Hi there!
It is not a browser issue, because in chrome I could also reproduce it on version 8.9.2. On version 8.9.3 the issue was gone, however, the hanging pop-up issue remains. The issue is reproduced on the official documentation site: [https://www.blazor.zone/table/edit](https://www.blazor.zone/table/edit)
### Steps:
1. Go to [https://www.blazor.zone/table/edit](https://www.blazor.zone/table/edit)
2. Scroll down to the top demo table and click delete extension button on the second row.
3. In the appeared confirmation pop-up click delete. 
4. After the popup hides and table gets refreshed click the delete extension button again on the second row.
5. In the appeared confirmation pop-up click delete. 

`Actual result`: the popup does not hide.

**Comment by ArgoZhang** [comment]
@ahurynovich thank you for this detailed information. I will fix this problem in the next version

**Comment by ArgoZhang** [comment]
@ahurynovich bump version `8.9.4-beta05` please have a try.
